version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - bodyclose
    - sqlclosecheck

  exclusions:
    paths:
      - tmp
      - migrations
      - _test\.go

run:
  timeout: 5m
