version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - bodyclose
    - sqlclosecheck
  exclusions:
    paths:
      - tmp
      - migrations

run:
  timeout: 3m